# Generated by Django 5.1.3 on 2025-10-30 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Circunscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('departamento', 'Departamento'), ('provincia_constitucional', 'Provincia Constitucional'), ('exterior', 'Exterior')], max_length=30)),
                ('poblacion', models.IntegerField(blank=True, null=True)),
                ('electores_registrados', models.IntegerField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_url', models.CharField(blank=True, max_length=500, null=True)),
                ('bandera_url', models.CharField(blank=True, max_length=500, null=True)),
                ('escudo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('numero_diputados', models.IntegerField(default=1)),
                ('numero_senadores', models.IntegerField(default=1)),
                ('latitud', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Circunscripción',
                'verbose_name_plural': 'Circunscripciones',
                'db_table': 'circunscripciones',
                'ordering': ['nombre'],
            },
        ),
    ]
