# Generated by Django 5.1.3 on 2025-10-30 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('circunscripciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulacroVoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8)),
                ('nombre_completo', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_eleccion', models.CharField(choices=[('presidencial', 'Presidencial'), ('senador_nacional', 'Senador Nacional'), ('senador_regional', 'Senador Regional'), ('diputado', 'Diputado'), ('parlamento_andino', 'Parlamento Andino')], max_length=25)),
                ('candidato_id', models.IntegerField()),
                ('mes_simulacro', models.IntegerField()),
                ('anio_simulacro', models.IntegerField()),
                ('fecha_voto', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('circunscripcion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='circunscripciones.circunscripcion')),
            ],
            options={
                'verbose_name': 'Voto Simulacro',
                'verbose_name_plural': 'Votos Simulacro',
                'db_table': 'simulacro_votos',
                'ordering': ['-fecha_voto'],
                'unique_together': {('dni', 'tipo_eleccion', 'mes_simulacro', 'anio_simulacro')},
            },
        ),
    ]
