# Generated by Django 5.1.3 on 2025-10-30 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PartidoPolitico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('siglas', models.CharField(max_length=50, unique=True)),
                ('logo_url', models.CharField(blank=True, max_length=500, null=True)),
                ('color_principal', models.CharField(blank=True, max_length=7, null=True)),
                ('tipo', models.CharField(choices=[('partido', 'Partido'), ('alianza', 'Alianza')], default='partido', max_length=10)),
                ('ideologia', models.CharField(blank=True, max_length=100, null=True)),
                ('fundacion_año', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('inhabilitado', 'Inhabilitado')], default='activo', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partido Político',
                'verbose_name_plural': 'Partidos Políticos',
                'db_table': 'partidos_politicos',
                'ordering': ['nombre'],
            },
        ),
    ]
